version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql-for-wsd-project
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: productParserDb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    name: mysql-data-wsd-project