spring:
  application:
    name: Product parser service

  datasource:
#    url: jdbc:mysql://localhost:3306/productParserDb
    url: jdbc:mysql://localhost:3306/productParserDb?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: WallStreetDocs
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        jdbc:
          batch_size: 100
    database-platform:


server:
  servlet:
    context-path: /productParser
